version: '3.3'

services:
  frontend:
    container_name: moyeo-client
    image: ${DOCKER_CLIENT_IMAGE}
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: npm run start
    networks:
      - backbone

  moyeo-nginx:
    container_name: moyeo-nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./dev/nginx:/etc/nginx/conf.d
      - ./dev/certbot/conf:/etc/letsencrypt
      - ./dev/certbot/www:/var/www/certbot
    depends_on:
      - frontend
    networks:
      - backbone
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./dev/certbot/conf:/etc/letsencrypt
      - ./dev/certbot/www:/var/www/certbot
    depends_on:
      - moyeo-nginx
    networks:
      - backbone
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  backbone:
    driver: bridge
