version: '3.3'

services:
  frontend:
    container_name: moyeo-client
    image: ${DOCKER_CLIENT_IMAGE}
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: npm run start
    networks:
      - backbone

  nginx:
    container_name: moyeo-nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./dev/nginx:/etc/nginx/conf.d
      - ./dev/certbot/conf:/etc/letsencrypt
      - ./dev/certbot/www:/var/www/certbot
    depends_on:
      - frontend
    networks:
      - backbone

  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./dev/certbot/conf:/etc/letsencrypt
      - ./dev/certbot/www:/var/www/certbot
    depends_on:
      - moyeo-nginx
    networks:
      - backbone

networks:
  backbone:
    driver: bridge
