version: '3.3'

services:
  frontend:
    container_name: moyeo-client
    image: ${DOCKER_CLIENT_IMAGE}
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: npm run start
    networks:
      - backbone

  nginx:
    container_name: moyeo-nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
    networks:
      - backbone

networks:
  backbone:
    driver: bridge
