version: '3.4'

services:
  frontend:
    container_name: moyeo-client
    image: frontend
    build:
      context: frontend
      dockerfile: ./Dockerfile
      target: development
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: npm run dev
