version: '3.4'

services:
  frontend:
    container_name: moyeo-client
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: npm run start
    networks:
      - backbone

  nginx:
    container_name: moyeo-nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
    networks:
      - backbone

networks:
  backbone:
    driver: bridge
# image: ${DOCKER_CLIENT_IMAGE}
