version: '3.3'

services:
  moyeo-server:
    container_name: moyeo-server-blue
    image: ${DOCKER_SERVER_IMAGE}
    environment:
      NODE_ENV: development
    ports:
      - 3001:3001
    command: npm run start:dev
    networks:
      - backbone

networks:
  backbone:
    external: true
