version: '3.4'

services:
  backend:
    container_name: moyeo-server
    image: ${DOCKER_SERVER_IMAGE}
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: npm run start:dev
