name: Backend Dev CI
run-name: ${{ github.actor }}가 실행함
on:
  pull-request:
    branches:
      - develop
    paths:
      - 'backend/**'
      - '.github/workflows/backend-dev-cd.yml'
      - '.github/workflows/slack-notification.yml'

jobs:
  Register-Docker-Image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './backend'
    outputs:
      status: ${{ job.status }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: docker registry login
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.NCP_DOCKER_REGISTRY }}
          username: ${{ secrets.NCP_ACCESS_KEY }}
          password: ${{ secrets.NCP_SECRET_KEY }}

      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: backend
          file: backend/Dockerfile
          tags: ${{ secrets.NCP_DOCKER_REGISTRY }}/moyeo-server:${{ github.SHA }}
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
#  CD:
#    needs: [Register-Docker-Image]
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: './backend'
#    outputs:
#      status: ${{ job.status }}
#    steps:
#      - name: deploy
#        uses: appleboy/ssh-action@master
#        env:
#          DOCKER_SERVER_IMAGE: ${{ secrets.NCP_DOCKER_REGISTRY }}/moyeo-server:${{ github.SHA }}
#        with:
#          host: ${{secrets.BACKEND_DEV_REMOTE_IP}}
#          username: ${{secrets.BACKEND_DEV_REMOTE_SSH_ID}}
#          password: ${{secrets.BACKEND_DEV_REMOTE_ADMIN_KEY}}
#          port: ${{secrets.BACKEND_DEV_REMOTE_SSH_PORT}}
#          envs: DOCKER_SERVER_IMAGE
#          script: ${{secrets.BACKEND_DEV_SSH_SCRIPT}}

  slack-notifications:
    needs: [Register-Docker-Image]
    if: ${{ always() }}
    uses: ./.github/workflows/slack-notification.yml
    with:
      title: 백엔드 개발용 CD
      status: '${{ needs.CD.outputs.status }}'
      commit_url: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}
    secrets:
      webhook_url: ${{ secrets.SLACK_NOTIFICATION_WEBHOOK_URL }}
