name: Backend Dev CI
run-name: ${{ github.actor }}가 실행함
on:
  pull_request:
    branches:
      - develop
jobs:
  CI:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './backend'
    outputs:
      status: ${{ job.status }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.18.1

      - name: dependency install
        run: npm install

      - name: lint test
        run: npm run lint

      - name: build
        run: npm run build

      - name: test
        run: npm run test

      - name: e2e test
        run: npm run test:e2e

      - name: docker register
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.NCP_DOCKER_REGISTRY }}
          username: ${{ secrets.NCP_ACCESS_KEY }}
          password: ${{ secrets.NCP_SECRET_KEY }}

  slack-notifications:
    needs: [CI]
    if: ${{ always() }}
    uses: ./.github/workflows/slack-notification.yml
    with:
      title: 백엔드 개발용 CI
      status: '${{ needs.CI.outputs.status }}'
      commit_url: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}
    secrets:
      webhook_url: ${{ secrets.SLACK_NOTIFICATION_WEBHOOK_URL }}
