name: Frontend CI
run-name: ${{ github.actor }}가 실행함
on: 
  pull_request:
    branches:
      - develop
jobs:
  CI:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './frontend'
    outputs:
      status: ${{ job.status }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: nodeJS
        uses: actions/setup-node@v3
        with: 
          node-version: 16.18.1

      - name: dependency install
        run: npm install

      - name: test
        run: npm run test-all

  lhci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './frontend'
    outputs:
      status: ${{ job.status }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: nodeJS
        uses: actions/setup-node@v3
        with: 
          node-version: 16.18.1
        
      - name: dependency install
        run: |
          npm install
      
      - name: Build
        run: |
          npm run build
      
      - name: lighthouse
        run: | 
          npm install -g @lhci/cli
          lhci autorun || echo "Fail to Run Lighthouse CI"

      - name: Format lighthouse score
        id: format_lighthouse_score
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const results = JSON.parse(fs.readFileSync("./frontend/lhci_reports/manifest.json"));
            let comments = "";

            results.forEach((result) => {
              const { summary, jsonPath } = result;
              const details = JSON.parse(fs.readFileSync(jsonPath));
              const { audits } = details;
              const formatResult = (res) => Math.round(res * 100);

              Object.keys(summary).forEach(
                (key) => (summary[key] = formatResult(summary[key]))
              );

              const score = (res) => (res >= 90 ? "🟢" : res >= 50 ? "🟠" : "🔴");

              const comment = [
                `⚡️ Lighthouse report!`,
                `| Category | Score |`,
                `| --- | --- |`,
                `| ${score(summary.performance)} Performance | ${summary.performance} |`
              ].join("\n");

              const detail = [
                `| Category | Score |`,
                `| --- | --- |`,
                `| ${score(
                  audits["first-contentful-paint"].score * 100
                )} First Contentful Paint | ${
                  audits["first-contentful-paint"].displayValue
                } |`
              ].join("\n");
              comments += comment + "\n" + detail + "\n";
            });
            core.setOutput('comments', comments)

      - name: comment PR
        uses: unsplash/comment-on-pr@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: ${{ steps.format_lighthouse_score.outputs.comments }}
  docker:
    needs: [CI]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './frontend'
    outputs:
      status: ${{ job.status }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: docker registry login
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.NCP_DOCKER_REGISTRY }}
          username: ${{ secrets.NCP_ACCESS_KEY }}
          password: ${{ secrets.NCP_SECRET_KEY }}

      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: frontend
          file: frontend/Dockerfile
          tags: ${{ secrets.NCP_DOCKER_REGISTRY }}/moyeo-client:latest
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  slack-notifications:
    needs: [CI, docker, lhci]
    if: ${{ always() }}
    uses: ./.github/workflows/slack-notification.yml
    with:
      title: 프론트엔드 개발용 CI
      status: 'CI : ${{ needs.CI.outputs.status }} && docker : ${{ needs.docker.outputs.status }} && lhci : ${{ needs.lhci.outputs.status }}'
      commit_url: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}
    secrets:
      webhook_url: ${{ secrets.SLACK_NOTIFICATION_WEBHOOK_URL }}